name: Docker Build and Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  
  pull-and-run-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          USERNAME: ${{ secrets.GHCR_USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: USERNAME, TOKEN
          script: |
            sudo docker login --username $USERNAME --password $TOKEN ghcr.io
            sudo docker-compose -f docker-compose.yml stop start_wars_server
            sudo docker system prune --force
            sudo docker-compose -f docker-compose.yml pull start_wars_server
            sudo docker-compose -f docker-compose.yml up -d start_wars_server